"""Add password reset fields to User

Revision ID: 1f3a0e12b872
Revises: 3e5f8a9c7d12
Create Date: 2026-04-16 08:28:49.621338

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1f3a0e12b872'
down_revision = '3e5f8a9c7d12'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('google_calendar_connections', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('google_calendar_connections_user_id_key'), type_='unique')
        batch_op.drop_index(batch_op.f('ix_google_calendar_connections_user_id'))
        batch_op.create_index(batch_op.f('ix_google_calendar_connections_user_id'), ['user_id'], unique=True)

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('password_reset_token', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('password_reset_token_expiry', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('password_reset_token_expiry')
        batch_op.drop_column('password_reset_token')

    with op.batch_alter_table('google_calendar_connections', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_google_calendar_connections_user_id'))
        batch_op.create_index(batch_op.f('ix_google_calendar_connections_user_id'), ['user_id'], unique=False)
        batch_op.create_unique_constraint(batch_op.f('google_calendar_connections_user_id_key'), ['user_id'], postgresql_nulls_not_distinct=False)

    # ### end Alembic commands ###
