"""Add MaintenanceOrder model and refactor photo/order relationships

Revision ID: 229653a88199
Revises: 68bbbc88c024
Create Date: 2026-05-01 15:10:39.428505

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '229653a88199'
down_revision = '68bbbc88c024'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('maintenance_orders',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('client_id', sa.Integer(), nullable=False),
    sa.Column('grave_id', sa.Integer(), nullable=False),
    sa.Column('planned_date', sa.Date(), nullable=True),
    sa.Column('completion_date', sa.Date(), nullable=True),
    sa.Column('total_price', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('notes', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['grave_id'], ['graves.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('maintenance_orders', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_maintenance_orders_client_id'), ['client_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_maintenance_orders_grave_id'), ['grave_id'], unique=False)

    with op.batch_alter_table('additional_services', schema=None) as batch_op:
        batch_op.alter_column('grave_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.create_index(batch_op.f('ix_additional_services_order_id'), ['order_id'], unique=False)
        batch_op.create_foreign_key(None, 'maintenance_orders', ['order_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('invoices', schema=None) as batch_op:
        batch_op.alter_column('grave_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.create_index(batch_op.f('ix_invoices_order_id'), ['order_id'], unique=False)
        batch_op.create_foreign_key(None, 'maintenance_orders', ['order_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('photos', schema=None) as batch_op:
        batch_op.alter_column('grave_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.create_index(batch_op.f('ix_photos_order_id'), ['order_id'], unique=False)
        batch_op.create_foreign_key(None, 'maintenance_orders', ['order_id'], ['id'], ondelete='CASCADE')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('photos', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_photos_order_id'))
        batch_op.alter_column('grave_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    with op.batch_alter_table('invoices', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_invoices_order_id'))
        batch_op.alter_column('grave_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    with op.batch_alter_table('additional_services', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_additional_services_order_id'))
        batch_op.alter_column('grave_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    with op.batch_alter_table('maintenance_orders', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_maintenance_orders_grave_id'))
        batch_op.drop_index(batch_op.f('ix_maintenance_orders_client_id'))

    op.drop_table('maintenance_orders')
    # ### end Alembic commands ###
