"""Add grave_id to additional_services, invoices, and photos

Revision ID: 3e5f8a9c7d12
Revises: a9d41c3e2b88
Create Date: 2026-04-30 00:00:00.000000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3e5f8a9c7d12'
down_revision = 'a9d41c3e2b88'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    
    # Add grave_id to additional_services
    with op.batch_alter_table('additional_services', schema=None) as batch_op:
        batch_op.add_column(sa.Column('grave_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'graves', ['grave_id'], ['id'], ondelete='CASCADE')
        batch_op.create_index(batch_op.f('ix_additional_services_grave_id'), ['grave_id'], unique=False)

    # Add grave_id to invoices
    with op.batch_alter_table('invoices', schema=None) as batch_op:
        batch_op.add_column(sa.Column('grave_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'graves', ['grave_id'], ['id'], ondelete='CASCADE')
        batch_op.create_index(batch_op.f('ix_invoices_grave_id'), ['grave_id'], unique=False)

    # Add grave_id to photos
    with op.batch_alter_table('photos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('grave_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'graves', ['grave_id'], ['id'], ondelete='CASCADE')
        batch_op.create_index(batch_op.f('ix_photos_grave_id'), ['grave_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    
    with op.batch_alter_table('photos', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_photos_grave_id'))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('grave_id')

    with op.batch_alter_table('invoices', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_invoices_grave_id'))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('grave_id')

    with op.batch_alter_table('additional_services', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_additional_services_grave_id'))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('grave_id')

    # ### end Alembic commands ###
