"""add cleaning model and reorganize photos

Revision ID: 4842a81bff99
Revises: 229653a88199
Create Date: 2026-05-01 15:18:18.832983

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '4842a81bff99'
down_revision = '229653a88199'
branch_labels = None
depends_on = None


def upgrade():
    # First, drop the foreign key constraints that reference maintenance_orders
    # This must be done BEFORE dropping the maintenance_orders table
    with op.batch_alter_table('additional_services', schema=None) as batch_op:
        batch_op.drop_constraint('additional_services_order_id_fkey', type_='foreignkey')
        batch_op.drop_index('ix_additional_services_order_id')
        batch_op.alter_column('grave_id', existing_type=sa.INTEGER(), nullable=False)

    with op.batch_alter_table('invoices', schema=None) as batch_op:
        batch_op.drop_constraint('invoices_order_id_fkey', type_='foreignkey')
        batch_op.drop_index('ix_invoices_order_id')
        batch_op.alter_column('grave_id', existing_type=sa.INTEGER(), nullable=False)

    with op.batch_alter_table('photos', schema=None) as batch_op:
        batch_op.drop_constraint('photos_order_id_fkey', type_='foreignkey')
        batch_op.drop_index('ix_photos_order_id')

    # Now drop the maintenance_orders table (it has no more dependencies)
    with op.batch_alter_table('maintenance_orders', schema=None) as batch_op:
        batch_op.drop_index('ix_maintenance_orders_client_id')
        batch_op.drop_index('ix_maintenance_orders_grave_id')

    op.drop_table('maintenance_orders')

    # Create the new cleanings table
    op.create_table('cleanings',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('grave_id', sa.Integer(), nullable=False),
        sa.Column('cleaning_number', sa.Integer(), nullable=False),
        sa.Column('performed_date', sa.Date(), nullable=True),
        sa.Column('created_at', sa.DateTime(), nullable=False),
        sa.Column('updated_at', sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(['grave_id'], ['graves.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('cleanings', schema=None) as batch_op:
        batch_op.create_index('ix_cleanings_grave_id', ['grave_id'], unique=False)

    # Add cleaning_id column to photos and link to cleanings
    with op.batch_alter_table('photos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('cleaning_id', sa.Integer(), nullable=True))
        batch_op.create_index('ix_photos_cleaning_id', ['cleaning_id'], unique=False)
        batch_op.create_foreign_key('photos_cleaning_id_fkey', 'cleanings', ['cleaning_id'], ['id'], ondelete='CASCADE')


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('photos', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('photos_order_id_fkey'), 'maintenance_orders', ['order_id'], ['id'], ondelete='CASCADE')
        batch_op.drop_index(batch_op.f('ix_photos_cleaning_id'))
        batch_op.create_index(batch_op.f('ix_photos_order_id'), ['order_id'], unique=False)
        batch_op.drop_column('cleaning_id')

    with op.batch_alter_table('invoices', schema=None) as batch_op:
        batch_op.create_foreign_key(batch_op.f('invoices_order_id_fkey'), 'maintenance_orders', ['order_id'], ['id'], ondelete='CASCADE')
        batch_op.create_index(batch_op.f('ix_invoices_order_id'), ['order_id'], unique=False)
        batch_op.alter_column('grave_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    with op.batch_alter_table('additional_services', schema=None) as batch_op:
        batch_op.create_foreign_key(batch_op.f('additional_services_order_id_fkey'), 'maintenance_orders', ['order_id'], ['id'], ondelete='CASCADE')
        batch_op.create_index(batch_op.f('ix_additional_services_order_id'), ['order_id'], unique=False)
        batch_op.alter_column('grave_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    op.create_table('maintenance_orders',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('client_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('grave_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('planned_date', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('completion_date', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('total_price', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=False),
    sa.Column('notes', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('status', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], name=op.f('maintenance_orders_client_id_fkey'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['grave_id'], ['graves.id'], name=op.f('maintenance_orders_grave_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('maintenance_orders_pkey'))
    )
    with op.batch_alter_table('maintenance_orders', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_maintenance_orders_grave_id'), ['grave_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_maintenance_orders_client_id'), ['client_id'], unique=False)

    with op.batch_alter_table('cleanings', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_cleanings_grave_id'))

    op.drop_table('cleanings')
    # ### end Alembic commands ###
