"""Add status and completion_date to graves

Revision ID: 68bbbc88c024
Revises: 1f3a0e12b872
Create Date: 2026-04-16 21:00:09.914220

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '68bbbc88c024'
down_revision = '1f3a0e12b872'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('additional_services', schema=None) as batch_op:
        batch_op.alter_column('grave_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('order_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.drop_index(batch_op.f('ix_additional_services_order_id'))
        batch_op.create_index(batch_op.f('ix_additional_services_grave_id'), ['grave_id'], unique=False)

    with op.batch_alter_table('google_calendar_connections', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('google_calendar_connections_user_id_key'), type_='unique')
        batch_op.drop_index(batch_op.f('ix_google_calendar_connections_user_id'))
        batch_op.create_index(batch_op.f('ix_google_calendar_connections_user_id'), ['user_id'], unique=True)

    with op.batch_alter_table('graves', schema=None) as batch_op:
        batch_op.alter_column('status',
               existing_type=sa.VARCHAR(length=30),
               type_=sa.String(length=50),
               existing_nullable=False,
               existing_server_default=sa.text("'plánováno'::character varying"))

    with op.batch_alter_table('invoices', schema=None) as batch_op:
        batch_op.alter_column('grave_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('order_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.drop_index(batch_op.f('ix_invoices_order_id'))
        batch_op.create_index(batch_op.f('ix_invoices_grave_id'), ['grave_id'], unique=False)

    with op.batch_alter_table('photos', schema=None) as batch_op:
        batch_op.alter_column('grave_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('order_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.drop_index(batch_op.f('ix_photos_order_id'))
        batch_op.create_index(batch_op.f('ix_photos_grave_id'), ['grave_id'], unique=False)

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('password_reset_token', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('password_reset_token_expiry', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('password_reset_token_expiry')
        batch_op.drop_column('password_reset_token')

    with op.batch_alter_table('photos', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_photos_grave_id'))
        batch_op.create_index(batch_op.f('ix_photos_order_id'), ['order_id'], unique=False)
        batch_op.alter_column('order_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('grave_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    with op.batch_alter_table('invoices', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_invoices_grave_id'))
        batch_op.create_index(batch_op.f('ix_invoices_order_id'), ['order_id'], unique=False)
        batch_op.alter_column('order_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('grave_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    with op.batch_alter_table('graves', schema=None) as batch_op:
        batch_op.alter_column('status',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=30),
               existing_nullable=False,
               existing_server_default=sa.text("'plánováno'::character varying"))

    with op.batch_alter_table('google_calendar_connections', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_google_calendar_connections_user_id'))
        batch_op.create_index(batch_op.f('ix_google_calendar_connections_user_id'), ['user_id'], unique=False)
        batch_op.create_unique_constraint(batch_op.f('google_calendar_connections_user_id_key'), ['user_id'], postgresql_nulls_not_distinct=False)

    with op.batch_alter_table('additional_services', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_additional_services_grave_id'))
        batch_op.create_index(batch_op.f('ix_additional_services_order_id'), ['order_id'], unique=False)
        batch_op.alter_column('order_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('grave_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###
