"""Add status and completion_date to graves

Revision ID: 68bbbc88c024
Revises: 1f3a0e12b872
Create Date: 2026-04-16 21:00:09.914220

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '68bbbc88c024'
down_revision = '1f3a0e12b872'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    
    # Note: grave_id columns and their indexes are added in migration 3e5f8a9c7d12
    # Here we just make the columns NOT NULL and handle the order_id columns
    with op.batch_alter_table('additional_services', schema=None) as batch_op:
        batch_op.alter_column('order_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.drop_index(batch_op.f('ix_additional_services_order_id'))

    with op.batch_alter_table('graves', schema=None) as batch_op:
        batch_op.alter_column('status',
               existing_type=sa.VARCHAR(length=30),
               type_=sa.String(length=50),
               existing_nullable=False,
               existing_server_default=sa.text("'plánováno'::character varying"))
        batch_op.add_column(sa.Column('completion_date', sa.Date(), nullable=True))

    with op.batch_alter_table('invoices', schema=None) as batch_op:
        batch_op.alter_column('order_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.drop_index(batch_op.f('ix_invoices_order_id'))

    with op.batch_alter_table('photos', schema=None) as batch_op:
        batch_op.alter_column('order_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.drop_index(batch_op.f('ix_photos_order_id'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('photos', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_photos_order_id'), ['order_id'], unique=False)
        batch_op.alter_column('order_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    with op.batch_alter_table('invoices', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_invoices_order_id'), ['order_id'], unique=False)
        batch_op.alter_column('order_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    with op.batch_alter_table('graves', schema=None) as batch_op:
        batch_op.drop_column('completion_date')
        batch_op.alter_column('status',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=30),
               existing_nullable=False,
               existing_server_default=sa.text("'plánováno'::character varying"))

    with op.batch_alter_table('additional_services', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_additional_services_order_id'), ['order_id'], unique=False)
        batch_op.alter_column('order_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###
