"""remove order_id columns

Revision ID: c1d87eaa274e
Revises: 4842a81bff99
Create Date: 2026-05-01 17:32:54.708987

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c1d87eaa274e'
down_revision = '4842a81bff99'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('additional_services', schema=None) as batch_op:
        batch_op.drop_column('order_id')

    with op.batch_alter_table('invoices', schema=None) as batch_op:
        batch_op.drop_column('order_id')

    with op.batch_alter_table('photos', schema=None) as batch_op:
        batch_op.drop_column('order_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('photos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('order_id', sa.INTEGER(), autoincrement=False, nullable=True))

    with op.batch_alter_table('invoices', schema=None) as batch_op:
        batch_op.add_column(sa.Column('order_id', sa.INTEGER(), autoincrement=False, nullable=True))

    with op.batch_alter_table('additional_services', schema=None) as batch_op:
        batch_op.add_column(sa.Column('order_id', sa.INTEGER(), autoincrement=False, nullable=True))

    # ### end Alembic commands ###
