"""Added Graveyard and relationships

Revision ID: f34b68bdb6da
Revises: 96f2a6b65966
Create Date: 2026-03-16 21:22:24.809098

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f34b68bdb6da'
down_revision = '96f2a6b65966'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('graveyards',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('graves', schema=None) as batch_op:
        batch_op.add_column(sa.Column('graveyard_id', sa.Integer(), nullable=False))
        batch_op.create_index(batch_op.f('ix_graves_graveyard_id'), ['graveyard_id'], unique=False)
        batch_op.create_foreign_key(None, 'graveyards', ['graveyard_id'], ['id'], ondelete='RESTRICT')
        batch_op.drop_column('cemetery_name')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('graves', schema=None) as batch_op:
        batch_op.add_column(sa.Column('cemetery_name', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_graves_graveyard_id'))
        batch_op.drop_column('graveyard_id')

    op.drop_table('graveyards')
    # ### end Alembic commands ###
